version: "3.7"
services:
        graphql-exporter:
            #image: quay.io/ricardbejarano/graphql_exporter
            #see https://github.com/ricardbejarano/graphql_exporter/pull/2
            image: lucaskohorst/graphql_exporter
            container_name: graphql-exporter
            hostname: graphql-exporter
            restart: always
            networks:
                - graphql

        grafana:
            container_name: grafana
            image: grafana/grafana:latest
            restart: unless-stopped
            hostname: grafana
            user: "0"
            volumes:
                - ./grafana/grafana.ini:/etc/grafana/grafana.ini
                - ./grafana/grafanaDatasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
                - ./grafana/grafanaDashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
                - ./grafana/dashboards:/var/lib/grafana/dashboards #load dashboards if you have any
                - ./grafana/grafana-storage:/var/lib/grafana #persistant storage
            ports: 
                - 3000:3000 #view grafana on the host
            networks:
                - graphql

        prometheus:
            container_name: prometheus
            image: prom/prometheus:latest
            user: root # https://github.com/prometheus/prometheus/issues/5976
            restart: unless-stopped
            hostname: prometheus
            command: --storage.tsdb.retention.time=7d --config.file=/etc/prometheus/prometheus.yml
            volumes:
                - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
            ports:
                 - 9090:9090 #view prometheus on host
            networks:
                - graphql

networks:
  theta:
    driver: bridge
