scrape_configs:
  - job_name: "graphql"
    metrics_path: "/query"
    params:
      endpoint:
        ["https://api.thegraph.com/subgraphs/name/<name>/<subgraph>"]
      query:
        - |
          {
           <QUERY>
          }
    static_configs:
      - targets: ["graphql-exporter:9199"] # graphql_exporter address:port

